# Generated by Django 3.1.5 on 2021-01-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('color', models.CharField(choices=[('black', 'черный'), ('white', 'белый')], max_length=50, verbose_name='Цвет блока')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Статей',
                'ordering': ['-created_at'],
            },
        ),
    ]
