# Generated by Django 3.2.13 on 2022-05-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
    ]
